name: CI

on:
  push:
    branches: [ master ]

env:
  S3_BUCKET_NAME: triptalk-build
  CODE_DEPLOY_APP_NAME: triptalk-cicd
  CODE_DEPLOY_GROUP_NAME: triptalk-cicd-group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run test
        run: ./gradlew test

      - name: Run build
        run: ./gradlew clean build -x test

      - name: Make zip file
        run: zip -r ./triptalk.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./triptalk.zip s3://$S3_BUCKET_NAME/triptalk.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $CODE_DEPLOY_GROUP_NAME --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=triptalk.zip
